### ISSUE TITLE
Error  (400) Bad Request

### ISSUE THREAD

**Issue by NetCenterH** [otaku-codes/StormKitty-Tweaked#1]
Hello,
I tried to use your fixed StromKitty but I got an error when Sending passwords archive to anonfile.
Please can you fix?
Here is the log file:

_____________________________________________________________________________________________
HideFile : Adding 'hidden' attribute to file C:\Users\***\Desktop\StormKittyBuild.exe
HideFile : Adding 'hidden' attribute to file C:\Users\***\Desktop\DotNetZip.dll
SetFileCreationDate : Changing file C:\Users\***\Desktop\DotNetZip.dll creation data
HideFile : Adding 'hidden' attribute to file C:\Users\***\Desktop\AnonFileApi.dll
SetFileCreationDate : Changing file C:\Users\***\Desktop\AnonFileApi.dll creation data
Wallets >> Failed collect wallet from registry
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à ‬⁫⁬‪‍‎⁬‮⁪‮​⁯‏‬‪​⁬​⁮‎‍‪⁪‌‪‪‪‪‏‍‮⁬‬⁫⁯⁮⁪‬‫‭‮.⁯‫⁮‌​⁭‎​⁮‮⁮‍⁫‬⁪⁬‎‪⁫‭‭‏⁮⁮⁯‬‌⁬⁪⁪‎⁮⁪⁭‏‭‍⁮‫‭‮(RegistryKey , String )
   à ‬⁫⁬‪‍‎⁬‮⁪‮​⁯‏‬‪​⁬​⁮‎‍‪⁪‌‪‪‪‪‏‍‮⁬‬⁫⁯⁮⁪‬‫‭‮.⁪⁯‪⁪‪⁬⁯‬⁪‌‪​⁮‏⁫‫​‌⁪⁬⁭​⁫‏‮‍⁯⁫‫⁫‎‭⁮‫‭⁫‎‫⁮‭‮(String , String )

Wallets >> Failed collect wallet from registry
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à ‬⁫⁬‪‍‎⁬‮⁪‮​⁯‏‬‪​⁬​⁮‎‍‪⁪‌‪‪‪‪‏‍‮⁬‬⁫⁯⁮⁪‬‫‭‮.⁯‫⁮‌​⁭‎​⁮‮⁮‍⁫‬⁪⁬‎‪⁫‭‭‏⁮⁮⁯‬‌⁬⁪⁪‎⁮⁪⁭‏‭‍⁮‫‭‮(RegistryKey , String )
   à ‬⁫⁬‪‍‎⁬‮⁪‮​⁯‏‬‪​⁬​⁮‎‍‪⁪‌‪‪‪‪‏‍‮⁬‬⁫⁯⁮⁪‬‫‭‮.⁪⁯‪⁪‪⁬⁯‬⁪‌‪​⁮‏⁫‫​‌⁪⁬⁭​⁫‏‮‍⁯⁫‫⁫‎‭⁮‫‭⁫‎‫⁮‭‮(String , String )

Steam >> Failed collect steam info
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à ⁪‮‎⁮‪‎‌‭‎⁬⁯⁬‍⁫​⁬⁬⁯⁭​⁮⁮‭⁭‭⁪‭‫‫‍‭⁮⁮⁬⁪‍‬‏⁪⁫‮.‬‎⁫‪⁫⁯‌‪⁫⁮⁫‪⁯‍‏‎‌⁯‎⁬⁯‌‪‭⁭​‮‌⁯‍‭‬⁬⁫⁯⁭‎⁮⁪⁪‮(String )

Wallets >> Failed collect wallet from registry
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à ‬⁫⁬‪‍‎⁬‮⁪‮​⁯‏‬‪​⁬​⁮‎‍‪⁪‌‪‪‪‪‏‍‮⁬‬⁫⁯⁮⁪‬‫‭‮.⁯‫⁮‌​⁭‎​⁮‮⁮‍⁫‬⁪⁬‎‪⁫‭‭‏⁮⁮⁯‬‌⁬⁪⁪‎⁮⁪⁭‏‭‍⁮‫‭‮(RegistryKey , String )
   à ‬⁫⁬‪‍‎⁬‮⁪‮​⁯‏‬‪​⁬​⁮‎‍‪⁪‌‪‪‪‪‏‍‮⁬‬⁫⁯⁮⁪‬‫‭‮.⁪⁯‪⁪‪⁬⁯‬⁪‌‪​⁮‏⁫‫​‌⁪⁬⁭​⁫‏‮‍⁯⁫‫⁫‎‭⁮‫‭⁫‎‫⁮‭‮(String , String )

Uplay >> Session not found
BattleNET >> Session not found
Report created
Archive ************ compression completed
Sending passwords archive to anonfile
Telegram >> EditMessage exception:
System.Net.WebException: Le serveur distant a retourné une erreur : (400) Demande incorrecte.
   à System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   à System.Net.WebClient.DownloadString(Uri address)
   à ‪‫‎⁭⁯‏‫​‪⁯‮‍⁪⁬⁮‪⁬⁮⁫⁪⁬⁭‏​‌‏⁫‪⁫⁮‍⁬‮⁬‮⁮⁫‭‬⁯‮.‌⁫⁫‮‎⁬‎⁯⁮⁯⁫⁬‫⁬‎⁪⁪‌‌⁪‭‪‮⁭‫‮‭⁯​⁭‭‬⁮‍‬‍⁫⁬⁪⁯‮(String , Int32 )

Sending report to telegram
Report sent to telegram bot
SelfDestruct : Running self destruct procedure...
_____________________________________________________________________________________________

**Comment by otaku-codes** [comment]
so i looked into this and and thigh i could figure out is that sine isp  have blocked anonfile website due to country laws, so the req is failing to upload file and there is nothingh to handle that error. The alternative can using gofile api or directly sending the file to telegram thorugh senddocument req. I will soon fix it when i get time.

**Comment by himanshupapola** [comment]
```
Sending passwords archive to anonfile
Telegram >> EditMessage exception:
System.Net.WebException: Le serveur distant a retourné une erreur : (400) Demande incorrecte.
```

ok so theres as edit message req is being sent which means that victim is running the malware second time and for edit message req to be sent sucessfully (200)  it need message id of the old senddocument req that was sent when the victim first time ran the malware in his pc. 

**Reason of this error:**
1. The most probable reason of this error is that you deleted the old message that was sent to you in telegram at the first time you ran malware . (this logic is just there so u don't get data from the same victim twice)

**How to fix:**
1. If u are debugging , to fix this go to appdata==> local/roaming (hidden folders visible OS and normal both)  look for a hidden folder with a long random name  and inside it there is file name msgid.dat (or just search for this file using file manager) there must be some Integer value within it delete it. All fixed.
2. Don't ever delete the victim  data that u recive on telegram this is supposed to be a feature btw where old victim data get edited instead of a new message everytime from same pc.

400 Error by telegram can be bcoz of various reason(text data length exceeded or other). If theres still issue i will recommend using [http debugger](https://www.httpdebugger.com/) to check what the actuall reponse of req  by telegram.

**Comment by NetCenterH** [comment]
"If u are debugging , to fix this go to appdata==> local/roaming (hidden folders visible OS and normal both) look for a hidden folder with a long random name and inside it there is file name msgid.dat (or just search for this file using file manager) there must be some Integer value within it delete it. All fixed."

This worked for me.
Thank u.
